/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'border-antique': '#E7DFCF',
        'surface-raised': '#F3EFE6',
        'surface-tint': '#944a23',
        'surface-card': '#FAF7F2',
        'canvas-cream': '#F6F1E7',
        'canvas-linen': '#FDFBF7',
        'gilded-amber': '#D97706',
        'gilded-radiance': '#FBBF24',
        'primary': '#592100',
        'primary-container': '#78350f',
        'on-primary': '#ffffff',
        'tertiary': '#1f3633',
        'tertiary-fixed': '#cde8e3',
        'tertiary-container': '#354d49',
        'surface': '#fff8f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fbf2f0',
        'surface-container': '#f5ecea',
        'surface-container-high': '#efe6e4',
        'surface-container-highest': '#e9e1df',
        'on-surface': '#1e1b1a',
        'on-surface-variant': '#54433c',
        'outline': '#87736a',
        'outline-variant': '#dac1b7',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
      },
      fontFamily: {
        'display': ['var(--font-eb-garamond)', 'serif'],
        'headline': ['var(--font-eb-garamond)', 'serif'],
        'body': ['var(--font-dm-sans)', 'sans-serif'],
        'label': ['var(--font-dm-sans)', 'sans-serif'],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter-sm': '1rem',
        'gutter': '1.5rem',
        'gutter-lg': '2rem',
      },
      borderRadius: {
        'xs': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
      }
    },
  },
  plugins: [],
}
